### PR TITLE
fix(preview): Maintain preview state during VS Code restart

### LINKED ISSUE #10: Add OJS/OMD Preview WebviewPanelSerializer
Gordon,

I added save as .ojs & .omd options to my JS notebook inspector:

https://github.com/RandomFractals/js-notebook-inspector/issues/54

Everything looks good, except OJS/OMD Preview webview is not restored on vscode restart.

before:

js-notebook-inspector-omd-save

that OMD Preview panel is gone after that vscode instance restart:

ojs-preview-blank-restore

Expected to see same thing as in pic 1.

It would be nice if you could add WebviewPanelSerializer for those custom .ojs/.omd panels.

See my notebook.view.ts for an example of implementing that api:

https://github.com/RandomFractals/js-notebook-inspector/blob/master/src/views/notebook.view.ts

### PR DESCRIPTION
**Pull request by GordonSmith**
Bump versions

Fixes #10

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@RandomFractals please review

**Comment by RandomFractals** [comment]
Gordon,

You also need to add webview panel extension activation event to `package.json`: 

https://code.visualstudio.com/api/references/activation-events#onWebviewPanel

in your case, I think it would be:

```
"activationEvents": [
        "onLanguage:ojs",
        "onLanguage:omd",
        "onWebviewPanel:ojs.preview"
    ],
```

**Comment by GordonSmith** [comment]
@RandomFractals I made some of those suggested changes - the getState / setState suggestion will take a little more refactoring than I have time for this morning...

**Comment by GordonSmith** [comment]
@RandomFractals - if your happy I will release this and open a new issue WRT to using the URI in the state?

**Comment by RandomFractals** [comment]
yeah, that's fine. Thanks for adding those changes.

**Pull request merged**
